### ISSUE TITLE
Help Needed!

### ISSUE THREAD

**Issue by monizb** [PavelApostolov/NodeJS-ReactJS-EmailSurveys#3]
Hey could you please help me get started when i Follow the usage steps i get the following error `Error: Cannot find module './dev'`, it would be really helpful if you could help me out!

**Comment by PavelApostolov** [comment]
Hi, you are right, but the reason that dev.js was not commited to this repository is that it contains sensitive data. See this article to understand how it is done - https://hackernoon.com/how-to-use-environment-variables-keep-your-secret-keys-safe-secure-8b1a7877d69c

You can try Stephen Grider's course this application is based on - https://www.udemy.com/course/node-with-react-fullstack-web-development/
